### ISSUE TITLE
Docs contain no instructions for configuration

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph-lightstep#5]
It seems multiple settings need to be set before links can be seen, but the docs imply that links should appear as soon as the extension is installed. The docs should document which settings are needed and where to obtain their values (e.g. where do I create a LightStep token, how do I know the project name).

**Comment by felixfbecker** [comment]
LightStep also uses the term "API Key", not "Token".

**Comment by sqs** [comment]
I think this was unintentional copy-pasta. I will remove it.

**Comment by sqs** [comment]
@felixfbecker `lightstep.token` actually comes from the TypeScript extension: https://sourcegraph.com/github.com/sourcegraph/sourcegraph-typescript@b79f932ea081123625b64699ac8a101f58fcfe3b/-/blob/package.json#L91:31.

The extension guides you through configuring it if it needs configuration. I added a commit just now to clarify this. There is only 1 setting that's needed (the project name), and it does tell you how to obtain this value both in the UI prompt and in the settings schema:

> LightStep project name (example: my-project in https://app.lightstep.com/my-project):

I think this is clear enough. If not, please reopen.
